Intial commit of objective optimization
aws-samples/amazon-personalize-samples pull request #120
Opened 2021-07-21 19:23 UTC by mikejgillespie

*Issue #, if available:*
N/A 

*Description of changes:*
Added a new workbook to demonstrate the objective optimization.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-31 01:22 UTC, james-jory requested changes
Looks great! Provided some suggestions for improving.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "items = items[['ITEM_ID', 'TITLE','SAVINGS', 'GENRE', 'ROYALTY']]\n",
`TITLE` and `ROYALTY` should be excluded from the CSV to be uploaded since we don't want to model (or need to filter) on those columns. Since you need those columns for inference time display, maybe save a local intermediate file with those columns first and then save a CSV without them which will be used to upload to Personalize.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "        }\n",
Drop `TITLE` and `ROYALTY` since we don't want to model or filter on either one of them.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "    name = \"personalize-demo-item-schema\",\n",
Might want to use a more specific schema name to avoid naming collisions if the user is running multiple notebooks.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "From this point, we will follow the same process from the first campaign, loading the interactions. We only want to include interactions with at least a rating of three, and we don't want to rec
Link to the notebook so the reader can learn more about the interactions dataset prep if they're just starting with this notebook and lack the context.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "    name = \"personalize-demo-schema\",\n",
Suggest using a more unique schema name that is specific to this notebook to avoid naming collisions. Or make the schema create logic more defensive.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "    name = \"personalize-launch-demo\"\n",
Use a more specific DSG name to avoid potential naming collisions.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "interaction_dataset_arn = create_dataset(\"INTERACTIONS\", schema_arn, 'personalize-launch-interactions')\n",
Use a more specific DS name to avoid naming collisions.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "dataset_import_job_arn = create_dataset_import_job(interaction_dataset_arn, \"s3://{}/{}\".format(bucket, filename), \"personalize-demo-import1\")\n",
Use a more specific import job name to avoid naming collisions.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "item_dataset_import_job_arn = create_dataset_import_job(item_dataset_arn, \"s3://{}/{}\".format(bucket, items_filename), \"personalize-demo-itemimport1\")\n",
Use a more specific import job name to avoid naming collisions.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "no_objective_optimization_solution = create_solution('movie-recommendation-max-royalties', 'OFF')"
Suggest renaming from "max-royalties" to "max-relevance" (or something) since Personalize is not trying to maximize royalties when sensitivity is `OFF` but rather is all about relevance and ignoring optimization objective.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +  },
Empty/unused code cell.

2021-07-31 01:22 UTC, james-jory commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +  }
Empty/unused code cells.

2021-08-03 18:08 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "This example assumes we are providing recommendations for a VOD streaming subscription service. The service receives allows users unlimited access to the video catalog, however the titles availa
I fixed in a next commit.

2021-08-03 18:08 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "Again, the data is coming from the MovieLens project, you can learn more about the data and potential uses by doing a web search during any of the waiting periods in the cells below. You will su
Hyperlink added

2021-08-03 18:09 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +  },
Deleted

2021-08-03 18:10 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "Be sure to update the `bucket` value if you customized it during deployment of the CloudFormation template. Click in the cell below to make changes."
I added the creation of a brand new S3 bucket to make the workbook completely self-contained. The cleanup code at the end also empties and deletes the bucket.

2021-08-03 18:10 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "The MovieLens GENRE field result above is one-hot encoded, but the items loaded into the personalization can accept arrays. Some pandas code to pull together the genres into a pipe delimited col
removed reference to one-hot encoding.

2021-08-03 18:15 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "Objective Optimization will optimize to the highest values of a field. In this case, we don't want to recommend titles that have the highest royalties, but those that offer the highest savinga.\
Changed working to: "In this case, we want to balance the relevance of the movie against the royalty expenses that will be incurred by the streaming service." Also - I took the advice of Anoop and made the royalty a negative number, this greatly simplified the code. Also, the distribution of the royalty was causing some dramatic impacts to the recommendations, so I change to distribution to be weighted to more titles with smaller royalties and a few titles with larger royalties.

2021-08-03 18:16 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "To property prioritize the movies with the lowest royalities, the movies with the lowest royalties need the highest numerical values. In this case, we will convert royalties to savings. This is
Reworded the paragraph.

2021-08-03 18:17 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "        }\n",
done, well removed SAVINGS and removed TITLE.

2021-08-03 18:19 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "    name = \"personalize-demo-schema\",\n",
added a suffix

2021-08-03 18:19 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "From this point, we will follow the same process from the first campaign, loading the interactions. We only want to include interactions with at least a rating of three, and we don't want to rec
link added

2021-08-03 18:20 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "    name = \"personalize-launch-demo\"\n",
Added a suffix

2021-08-03 18:21 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "interaction_dataset_arn = create_dataset(\"INTERACTIONS\", schema_arn, 'personalize-launch-interactions')\n",
Added a suffix

2021-08-03 18:22 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "item_dataset_import_job_arn = create_dataset_import_job(item_dataset_arn, \"s3://{}/{}\".format(bucket, items_filename), \"personalize-demo-itemimport1\")\n",
Added a suffix

2021-08-03 18:22 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "no_objective_optimization_solution = create_solution('movie-recommendation-max-royalties', 'OFF')"
renamed

2021-08-03 18:22 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +  }
removed

2021-08-03 18:23 UTC, mikejgillespie commented on next_steps/core_use_cases/objective_optimization/objective-optimization.ipynb
> +    "items = items[['ITEM_ID', 'TITLE','SAVINGS', 'GENRE', 'ROYALTY']]\n",
Removed from CSV in S3, but kept locally for lookup.

2021-08-03 21:35 UTC, james-jory requested changes
Looking good. The only feedback I have now is that the notebook has output for the first 15 cells but no output through the rest of the notebook. I suggest either having a clean notebook with no output or have the output for all cells.

2021-08-03 21:59 UTC, mikejgillespie commented
> Looking good. The only feedback I have now is that the notebook has output for the first 15 cells but no output through the rest of the notebook. I suggest either having a clean notebook with no output or have the output for all cells.

I cleared all the outputs and retested it. Looks like it is all working.

2021-08-05 15:52 UTC, james-jory commented
LGTM

2021-08-05 16:36 UTC, merged